const bgByType = {
    normal: "bg-gradient-to-t from-stone-400 to-stone-600",
    fighting: "bg-gradient-to-t from-amber-700 to-amber-900",
    flying: "bg-gradient-to-t from-pink-700 to-pink-800",
    poison: "bg-gradient-to-t from-purple-500 to-purple-800",
    ground: "bg-gradient-to-t from-yellow-500 to-red-800",
    rock: "bg-gradient-to-t from-gray-500",
    bug: "bg-gradient-to-t from-yellow-500",
    ghost: "bg-gradient-to-t from-purple-500",
    steel: "bg-gradient-to-t from-gray-500 to-red-200",
    fire: "bg-gradient-to-t from-orange-300 to-orange-500",
    water: "bg-gradient-to-t from-blue-500 to-blue-200",
    grass: "bg-gradient-to-t from-green-300 to-green-500",
    electric: "bg-gradient-to-t from-gray-500 to-blue-200",
    psychic: "bg-gradient-to-t from-teal-500 to-blue-200",
    ice: "bg-gradient-to-t from-sky-200 to-blue-800",
    dragon: "bg-gradient-to-t from-red-400 to-red-600",
    dark: "bg-gradient-to-t from-neutral-400 to-neutral-900",
    fairy: "bg-gradient-to-t from-pink-400 to-blue-900",
    unknown: "bg-gradient-to-t from-purple-500 to-purple-800",
    shadow: "bg-gradient-to-t from-amber-700 to-amber-900",
  };

  const borderByType = {
    normal: "border-stone-600",
    fighting: "border-amber-800",
    flying: "border-pink-800",
    poison: "border-purple-800",
    ground: "border-yellow-500",
    rock: "border-gray-500",
    bug: "border-yellow-300",
    ghost: "border-blue-700",
    steel: "border-gray-500",
    fire: "border-orange-500",
    water: "border-blue-500",
    grass: "border-green-500",
    electric:"border-slate-500",
    psychic: "border-teal-500",
    ice: "border-sky-500",
    dragon: "border-red-700",
    dark: "border-neutral-950",
    fairy: "border-pink-300",
    unknown: "border-purple-800",
    shadow: "border-blue-500",
  };
  
  export { bgByType, borderByType };